### ISSUE TITLE
add Practice Exam Tests

### ISSUE THREAD

**Issue by ronaldo-barros** [walidshaari/Kubernetes-and-Cloud-Native-Associate#7]
add this Practice Exam Tests:

https://www.udemy.com/course/kubernetes-and-cloud-native-associate-kcna/

**Comment by ronaldo-barros** [comment]
incluide

**Comment by walidshaari** [comment]
it is in the other branch, not merged yet  https://github.com/walidshaari/Kubernetes-and-Cloud-Native-Associate/tree/KCNA-series01
